from setuptools import setup, find_packages

setup(
    name="voice-manipulation-detection",
    version="0.1.0",
    author="Akhchine Ismail & Tahiri Soufiane",
    author1_email="tahirisoufiane.406@gmail.com",
    author2_email="ismailae256@gmail.com",
    description="Voice manipulation detection using RNN and Transformers",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    url="https://github.com/Dev-AndroidApp/voice-manipulation-detection.git",
    packages=find_packages(),
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Science/Research",
        "Topic :: Scientific/Engineering :: Artificial Intelligence",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
    ],
    python_requires=">=3.8",
    install_requires=[
        "torch>=2.0.0",
        "torchaudio>=2.0.0",
        "numpy>=1.24.0",
        "pandas>=2.0.0",
        "scikit-learn>=1.3.0",
        "librosa>=0.10.0",
        "soundfile>=0.12.0",
        "audiomentations>=0.30.0",
        "matplotlib>=3.7.0",
        "seaborn>=0.12.0",
        "pyyaml>=6.0",
        "tqdm>=4.65.0",
        "tensorboard>=2.13.0",
    ],
    extras_require={
        "dev": [
            "pytest>=7.4.0",
            "black>=23.0.0",
            "flake8>=6.0.0",
            "mypy>=1.4.0",
            "jupyter>=1.0.0",
        ],
        "wandb": ["wandb>=0.15.0"],
    },
)