"""
Generate TTS (Text-to-Speech) synthetic speech for testing spoof detection.
Uses pyttsx3 (offline, no API key needed) or edge-tts (realistic Microsoft voices).
"""
import os
import numpy as np
import soundfile as sf

# Try to use edge-tts (better quality, free Microsoft voices)
try:
    import edge_tts
    import asyncio
    EDGE_TTS_AVAILABLE = True
except ImportError:
    EDGE_TTS_AVAILABLE = False
    print("edge-tts not installed. Run: pip install edge-tts")

# Fallback to pyttsx3 (offline, lower quality)
try:
    import pyttsx3
    PYTTSX3_AVAILABLE = True
except ImportError:
    PYTTSX3_AVAILABLE = False
    print("pyttsx3 not installed. Run: pip install pyttsx3")

SAMPLE_RATE = 16000
OUTPUT_DIR = os.path.dirname(os.path.abspath(__file__))

def generate_tts_edge(text, output_path, voice='en-US-AriaNeural'):
    """Generate TTS using Microsoft Edge voices (realistic, online required)."""
    if not EDGE_TTS_AVAILABLE:
        print("edge-tts not available. Install: pip install edge-tts")
        return False

    async def tts():
        communicate = edge_tts.Communicate(text=text, voice=voice)
        await communicate.save(output_path)

    try:
        asyncio.run(tts())
        print(f"✅ Generated TTS (edge): {output_path}")
        return True
    except Exception as e:
        print(f"❌ edge-tts failed: {e}")
        return False


def generate_tts_pyttsx3(text, output_path, rate=150):
    """Generate TTS using pyttsx3 (offline, lower quality)."""
    if not PYTTSX3_AVAILABLE:
        print("pyttsx3 not available. Install: pip install pyttsx3")
        return False

    try:
        engine = pyttsx3.init()
        engine.setProperty('rate', rate)  # Words per minute
        engine.setProperty('volume', 0.9)  # 0-1

        # Try to use SAPI5 (Windows) voice
        voices = engine.getProperty('voices')
        if len(voices) > 0:
            engine.setProperty('voice', voices[0].id)

        engine.save_to_file(text, output_path)
        engine.runAndWait()

        print(f"✅ Generated TTS (pyttsx3): {output_path}")
        return True
    except Exception as e:
        print(f"❌ pyttsx3 failed: {e}")
        return False


def generate_tts_with_noise(text, output_path, snr_db=20):
    """Generate TTS and add background noise for realism."""
    temp_path = output_path.replace('.wav', '_clean.wav')

    # Generate TTS first
    success = False
    if EDGE_TTS_AVAILABLE:
        success = generate_tts_edge(text, temp_path)
    elif PYTTSX3_AVAILABLE:
        success = generate_tts_pyttsx3(text, temp_path)

    if not success:
        print("Failed to generate TTS")
        return False

    # Load and add noise
    audio, sr = sf.read(temp_path)
    if len(audio.shape) > 1:
        audio = audio.mean(axis=1)

    # Resample to 16kHz if needed
    if sr != SAMPLE_RATE:
        import librosa
        audio = librosa.resample(audio, orig_sr=sr, target_sr=SAMPLE_RATE)

    # Add white noise
    noise = np.random.normal(0, 0.01, len(audio))
    audio_noisy = audio + noise

    # Normalize
    max_val = np.max(np.abs(audio_noisy))
    if max_val > 0:
        audio_noisy = audio_noisy / max_val * 0.95

    sf.write(output_path, audio_noisy, SAMPLE_RATE)
    os.remove(temp_path)

    print(f"✅ Generated TTS with noise: {output_path}")
    return True


if __name__ == '__main__':
    print("="*60)
    print("TTS ATTACK GENERATOR")
    print("="*60)

    # Test phrases
    phrases = [
        "Hello, this is a test of the text to speech system.",
        "The quick brown fox jumps over the lazy dog.",
        "This is synthetic speech generated by artificial intelligence.",
    ]

    print(f"\nAvailable TTS backends:")
    print(f"  edge-tts (online, realistic): {EDGE_TTS_AVAILABLE}")
    print(f"  pyttsx3 (offline, lower quality): {PYTTSX3_AVAILABLE}")

    if not (EDGE_TTS_AVAILABLE or PYTTSX3_AVAILABLE):
        print("\n⚠️  No TTS backend available!")
        print("Install one: pip install edge-tts pyttsx3")
        exit(1)

    print("\nGenerating TTS samples...\n")

    for i, phrase in enumerate(phrases, 1):
        output_path = os.path.join(OUTPUT_DIR, f'tts_attack_{i}.wav')
        print(f"[{i}/{len(phrases)}] \"{phrase}\"")

        if EDGE_TTS_AVAILABLE:
            generate_tts_edge(phrase, output_path)
        else:
            generate_tts_pyttsx3(phrase, output_path)

    print("\n" + "="*60)
    print("✅ Done! Test files generated:")
    for i in range(1, len(phrases) + 1):
        print(f"   tts_attack_{i}.wav")
    print("\nLoad these in the app to test spoof detection!")
    print("="*60)

