import os
import asyncio
import numpy as np
import soundfile as sf

try:
    import edge_tts
    EDGE_TTS_AVAILABLE = True
except ImportError:
    EDGE_TTS_AVAILABLE = False

SAMPLE_RATE = 16000
OUTPUT_DIR = os.path.dirname(os.path.abspath(__file__))


async def generate_tts_edge(text, output_path, voice='en-US-AriaNeural'):
    if not EDGE_TTS_AVAILABLE:
        return False
    try:
        communicate = edge_tts.Communicate(text=text, voice=voice)
        await communicate.save(output_path)

        audio, sr = sf.read(output_path)
        if len(audio.shape) > 1:
            audio = audio.mean(axis=1)

        if sr != SAMPLE_RATE:
            try:
                import librosa
                audio = librosa.resample(audio, orig_sr=sr, target_sr=SAMPLE_RATE)
            except ImportError:
                idx = np.linspace(0, len(audio) - 1, int(len(audio) * SAMPLE_RATE / sr))
                audio = np.interp(idx, np.arange(len(audio)), audio)

        max_val = np.max(np.abs(audio))
        if max_val > 0:
            audio = audio / max_val * 0.95

        sf.write(output_path, audio.astype(np.float32), SAMPLE_RATE)
        print(f"Generated: {output_path}")
        return True
    except Exception as e:
        print(f"Failed: {e}")
        return False


async def main():
    phrases = [
        "Hello, this is a test of the text to speech system.",
        "The quick brown fox jumps over the lazy dog.",
        "This is synthetic speech generated by artificial intelligence.",
    ]

    if not EDGE_TTS_AVAILABLE:
        print("edge-tts not installed. Run: pip install edge-tts")
        exit(1)

    for i, phrase in enumerate(phrases, 1):
        output_path = os.path.join(OUTPUT_DIR, f'tts_attack_{i}.wav')
        print(f"[{i}/{len(phrases)}] \"{phrase}\"")
        await generate_tts_edge(phrase, output_path)

    print(f"Done. {len(phrases)} TTS samples generated.")


if __name__ == '__main__':
    asyncio.run(main())
